platform :ios, '9.0'
inhibit_all_warnings!

use_frameworks!


target 'Delicacy' do
    pod 'Alamofire', '~> 4.7.2' # Elegant HTTP Networking in Swift
    pod 'SnapKit', '~> 4.0.0' # Harness the power of auto layout with a simplified, chainable, and compile time safe syntax
    pod 'Kingfisher', '~> 4.10.0' # A lightweight and pure Swift implemented library for downloading and cacheing image from the web
#    pod 'RxSwift', '~> 4.0' # RxSwift is a Swift implementation of Reactive Extensions
#    pod 'RxCocoa', '~> 4.0' # RxSwift Cocoa extensions
    pod 'Toast-Swift', '~> 4.0.0' # A Swift extension that adds toast notifications to the UIView object class
    pod 'WechatOpenSDK'
    pod 'PPBadgeViewSwift'
    pod 'JPush'
    
end

